### ISSUE TITLE
Lag spike when switching weapons.

### ISSUE THREAD

**Issue by QazCetelic** [desertkun/brainout#23]
A lag spike occurs, freezing the game when switching weapons. This does not happen reliably, and it is therefore hard to reproduce which specific switch from which weapon actually causes it.

**Comment by TannicArcher** [comment]
This project has been abandoned and I think no one will help you, just waiting for a new game like this but not much and everything will be fixed there

**Comment by kemzops** [comment]
> This project has been abandoned and I think no one will help you, just waiting for a new game like this but not much and everything will be fixed there

Same issue here, i hope this project will not be abandoned completely, i really like this game.

**Comment by QazCetelic** [comment]
I can't reproduce this on the latest version :thinking:
